spring:
  profiles:
    active: test-run,remote
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      example:
        promotionengine: DEBUG
